config/routes.rb
Rails.application.routes.draw do
  # add CRUD methods to restaurants except update and destroy since visitors are not allowed to do it
  resources :restaurants, except: [:update, :destroy] do
    # add CRUD methods to reviews only for new and create
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name, :address
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates_presence_of :content
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all # get the restaurants list
  end

  def new
    @restaurant = Restaurant.new
  end

  # if form details are valid, redirect to entered restaurant details page else render the same form
  def create
    @restaurant = Restaurant.new(res_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  # get the restaurant by it's id
  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  # strong params for security
  def res_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <!-- For detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<h1>Restaurants List :</h1>
<% @restaurants.each_with_index do |rest, index| %>
<div>
<%= "#{index+1}. #{rest.name}" %>
</div>
<% end %>

<br>

<%= link_to "Click to add a restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h2>Add a new restaurant !</h2>

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.submit "Add", class: "btn btn-primary" %>
<% end %>

<br>
<%= link_to "Back to restaurants list", restaurants_path %>

app/views/restaurants/show.html.erb
<h1>Details of a restaurant</h1>
<h5><%= "Address : #{@restaurant.address}" %></h4>
<h5><%= "Category : #{@restaurant.category}" %></h5>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>